spring:
  application:
    name: ai-quiz-generator
  
  # MongoDB Configuration
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/quiz_generator_db}
  
  # Jackson Configuration
  jackson:
    default-property-inclusion: NON_NULL
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

# Server Configuration
server:
  port: ${PORT:8080}
  servlet:
    context-path: /api/v1
  error:
    include-message: always
    include-binding-errors: always

# Custom Application Properties
app:
  # JWT Configuration
  jwt:
    secret: ${JWT_SECRET:mySecretKey123456789012345678901234567890}
    expiration: 86400000 # 24 hours in milliseconds
    refresh-expiration: 604800000 # 7 days in milliseconds
  
  # Gemini AI Configuration
  gemini:
    api-key: ${GEMINI_API_KEY:your-gemini-api-key-here}
    base-url: https://generativelanguage.googleapis.com/v1beta
    model: gemini-1.5-flash
    max-tokens: 2048
    temperature: 0.7
  
  # CORS Configuration
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:3001
      - http://localhost:5173
      - ${FRONTEND_ORIGIN:https://your-frontend.onrender.com}
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers:
      - "*"
    allow-credentials: true

# Logging Configuration
logging:
  level:
    com.quizApp: DEBUG
    org.springframework.security: INFO
    org.springframework.web: INFO
    org.mongodb: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
